run:
  timeout: 10m

linters-settings:
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/onflow/flow-go/

  gosec:
    # To select a subset of rules to run.
    # Available rules: https://github.com/securego/gosec#available-rules
    includes:
      - G401
      - G402
      - G501
      - G502
      - G503
      - G505

  staticcheck:
    # Disable SA1019 to allow use of deprecated label
    checks: ["all", "-SA1019"]

  custom:
    example:
      type: module
      # Description is optional
      description: The description of the linter. This is optional, but shows up when running `golangci-lint linters`.
      # Original-url is optional, and is only used for documentation purposes.
      original-url: github.com/golangci/example-plugin-module-linter
      settings:
        one: Foo
        two:
          - name: Bar
        three:
          name: Bar
    structwrite:
      type: module
      description: "disallow struct field writes outside constructor"
      original-url: "github.com/yourname/golangci-structwrite"
      settings:
        structs:
          - Header

linters:
  disable-all: true
  enable:
#    - goimports
#    - gosec
    - structwrite

issues:
  exclude-rules:
    - path: _test\.go # disable some linters on test files
      linters:
        - unused
        - structwrite
    # typecheck currently not handling the way we do function inheritance well
    # disabling for now
    - path: 'cmd/access/node_build/*'
      linters:
        - typecheck
    - path: 'cmd/observer/node_builder/*'
      linters:
        - typecheck
    - path: 'follower/*'
      linters:
        - typecheck
